from backpack import *;

answer = [['djmvowgbvz', 'eyrvvitejc', 'jbnhbxgqwf', 'vgfkblrinn', 'wpnunhbjyk'], ['bgcxhaxvpb', 'dvtrfwisvo', 'emcpxrvcel', 'rtwvjpvfhc'], ['answhjwszn', 'cutbmsdntu', 'miecyjbopm', 'uhcoqzxxzc', 'undpqwavia'], ['alcgrsnwyi', 'bynjmvxqtn', 'laiuspdoid', 'tetnzpkyrw'], ['glexebjkic', 'pylkhoszpn', 'roumouliwq', 'vwuyeagsnu', 'xhgcdxktmm'], ['jybuoawyse', 'kckzgwljii', 'oeeomusdjs', 'qjusejlrow', 'vyrdpazxnd'], ['bfyldjvadl', 'iuvcwqkjal', 'jcqfhftvpq', 'olscyntokg', 'rwdrhayugc', 'tyrrxeecsw'], ['ahupebcsqt', 'dqknrupwxu', 'pxtpumnrdr', 'xitfnojila', 'yusizzfbwe', 'zvcxbbwsdp'], ['cqykfrmqxn', 'fnmcodjmhk', 'hdmuhailhg', 'hiioayslfs', 'lidrcdvlul', 'xeykjevaoe', 'ybvzstcomn', 'zhdstvckbu'], ['ceblnrvsqw', 'lwjeuvdqff', 'mgqpqilaqj', 'npelepakun', 'rlybmahigu']];
answer1 = [['cambtohddv', 'cklemxfpja', 'dfiaimfixq', 'dkmnwtuhom', 'eidugyzede', 'fjcavuxlor', 'fxwynpotyc', 'jemilzkifb', 'kdqcxpfcaj', 'ntmjebinmi', 'ocuqhwboiu', 'ptpivjukxr', 'qjzbynckon', 'tpvrlqgnrg', 'wceqwjspwp', 'ytqjntdjlt', 'yuwwezwthb'], ['boxzjbxmgf', 'ehicfmtjjl', 'lktleokuco', 'lvavehydjh', 'ppsetvjqbg', 'sggmklzebm', 'ufhofxxbsj', 'vhibcismde'], ['gyrkapwrdz', 'hvyrysvptk', 'iqzqmtdkhn', 'meyufjdguf', 'qakekccien', 'vwylwctbyh', 'xezjgtvgoq', 'xkscmkrvnk'], ['aulotodbdv', 'crcsxvwinx', 'dmtgipspzt', 'dzahtyctwx', 'kcqfalyfil', 'otmhikkqta', 'sjwfaemzdp', 'udyztbiaod', 'ugnwztrwwt', 'woyjlgttqk'], ['bdslhwstkq', 'bzgqhxecgn', 'glzbkbuupk', 'jsxowbfwwm', 'qsagojkizl', 'sjddpfopdp', 'tniapwyvqe', 'zxiuvapwuu'], ['czdhphobat', 'dhfqdbflag', 'jnukzrsiuo', 'netbhvnwrj', 'nuukblpxqo', 'qbiyawwwhx', 'wgqormjlut', 'whzhwlvvnk'], ['bcrknrfliw', 'etlcqhylsd', 'fcwzohnrni', 'fuukuhfdcd', 'gsbwrltifj', 'ksjlghvqli', 'lhggyqzaur', 'nsxunbgyzx', 'tepwpozlvg', 'twiyuexpld', 'vdhhcdfytp', 'wliykigzzw', 'zdlopccubz', 'zfwryiksui', 'zkybemsusj', 'zpjuybblta'], ['azwoqbnxrf', 'daxugtmbxw', 'ecmebzdqqf', 'fgpsdmuhfn', 'jmobodbkcx', 'kddedjycll', 'lkmnncplcp', 'msseawsdiz', 'rewvphoshm', 'teblrebyax', 'vhywuaecpg', 'xfgeudaebk', 'zwmnqilyog'], ['dbigxvkuga', 'favmulsvem', 'fksmzipsmp', 'jtznnunmhd', 'keajyqzaxd', 'okjuatlzlq', 'qyrudzjorf', 'sizgpdnqsc', 'sqtxxfsmfg', 'tucozabnby', 'whcgyaxbmp', 'xbbisogymd', 'yndbubgfoi', 'yzzpuwboxd', 'zwaxcvlaxw'], ['crthecrcnr', 'cwrzsdqvlt', 'dunxdglatv', 'fjkkhlcost', 'iopmboiuub', 'iuwcsijrkh', 'kiflzpbpla', 'ninckllpaf', 'oncfvtenof', 'qpkegbsebw', 'sddrhsyfqn', 'yjbrtmxpba']];

result = solveKnapsackFile("problems_size10.txt");
result1 = solveKnapsackFile("problems_size20.txt");

print(result == answer, result1 == answer1);
